name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build the Angular app
        run: ng build --prod

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          FOLDER: dist
